AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Lambdas using DynamoDB

  '
Globals:
  Function:
    Timeout: 20
Resources:
  InsertTest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://stratocumulus-bucket/109814b3fcc8aa49c2bbc45682c9d2e4
      Handler: handler.InsertTestHandler::handleRequest
      Policies: AmazonDynamoDBFullAccess
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /insert
            Method: post
  DeleteTest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://stratocumulus-bucket/9e32a8d1522deb4cc39cec6c63daf047
      Handler: handler.DeleteTestHandler::handleRequest
      Policies: AmazonDynamoDBFullAccess
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /delete
            Method: delete
  GetTest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://stratocumulus-bucket/53b059babe09fe9fde1179fcea29068a
      Handler: handler.GetTestHandler::handleRequest
      Policies: AmazonDynamoDBFullAccess
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /get
            Method: get
  UpdateTest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://stratocumulus-bucket/ac6d937bff7d87a751e008892c516fb2
      Handler: handler.UpdateTestHandler::handleRequest
      Policies: AmazonDynamoDBFullAccess
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /update
            Method: update
