AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Lambdas using DynamoDB

  '
Globals:
  Function:
    Timeout: 20
Resources:
  InsertTest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://stratocumulus-bucket/4e7981c670399cec0c4ec0385eec64aa
      Handler: handler.InsertTestHandler::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /insert
            Method: post
  DeleteTest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://stratocumulus-bucket/f3960392589e5118e4887ede590a5a1c
      Handler: handler.DeleteTestHandler::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /delete
            Method: delete
  GetTest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://stratocumulus-bucket/0cc24ad4c740d209d6fcfcb0ab16ee0e
      Handler: handler.GetTestHandler::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /get
            Method: get
