AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Lambdas using DynamoDB

  '
Globals:
  Function:
    Timeout: 20
Resources:
  InsertTest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://stratocumulus-bucket/a621579b3357e614da1323881199ffaa
      Handler: handler.InsertTestHandler::handleRequest
      Runtime: java8
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /insert
            Method: post
